config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :friend_requests, only: [:create, :destroy]
  resources :users
  resources :friendships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  # I decided to use class methods instead of scope
  # because I need these to return nil when no
  # matching records are found
  def self.to(user)
    find_by(receiver_id: user.id)
  end

  # Rails already defines a 'from' method for FriendRequest
  # which is why I am using custom_from
  def self.custom_from(user)
    find_by(sender_id: user.id)
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :sent_friend_reqs, class_name: 'FriendRequest', foreign_key: 'sender_id'
  has_many :friend_req_receivers, through: :sent_friend_reqs, source: :receiver

  has_many :received_friend_reqs, class_name: 'FriendRequest', foreign_key: 'receiver_id'
  has_many :friend_req_senders, through: :received_friend_reqs, source: :sender

  has_many :friends, class_name: 'Friendship'

  validates :first_name, :last_name, presence: true
  validates :password, presence: true, allow_nil: true
  validates :email, presence: true, uniqueness: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  include SessionsHelper

  private

  def require_login
    unless logged_in?
      flash.alert = "You must login first"
      redirect_to login_url
    end
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :verify_original_req, only: [:create]

  def create
    current_user.sent_friend_reqs.create!(receiver_id: params[:receiver_id])
    redirect_to user_path(params[:receiver_id])
  end

  private

  def verify_original_req 
    receiver = User.find(params[:receiver_id])

    if current_user.sent_friend_reqs.to(receiver) || receiver.sent_friend_reqs.to(current_user)
      redirect_to user_path(params[:receiver_id])
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  include FriendRequestsHelper

  before_action :verify_friend_req

  def create
    # Only the friendreq receiver can 'create' a friendship
    current_user.friends.create(friend_id: @sender.id)
    @sender.friends.create(friend_id: current_user.id)

    @friend_req.delete
    redirect_back fallback_location: root_path
  end

  private

  def verify_friend_req
    @sender = User.find(params[:sender_id])
    @friend_req = current_user.received_friend_reqs.find_by(sender_id: @sender.id)
    redirect_to root_url unless @friend_req
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])

    if @user&.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to root_url
    else
      flash.now[:alert] = "Email or password is invalid."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Successfully logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "User successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
  def delete_friend_request(sender)
    current_user.received_friend_reqs.delete_by(sender_id: sender.id)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.haml
#flash
  - flash.each do |flash_type, message|
:

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <p>
  Made with love using 
  <%= link_to 'Ruby on Rails', "http://www.rubyonrails.org/", target: :blank %> and 
  <%= link_to "StimulusReflex", "https://docs.stimulusreflex.com/", target: :blank %>
  </p>
</footer>

app/views/layouts/_header.html.haml
%section#nav-header
  %header
    %h1
      = link_to 'FakeBook', root_path

  %nav
    - if logged_in?
      %ul
        %li= link_to "Logout", logout_path, method: :delete
    - else
      %ul
        %li= link_to "Login", login_path
        %li= link_to "Signup", signup_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main class="container">
      <% flash.each do |message_type, message| %>
        <%= tag.div message, class: "flash-#{ message_type }" %>
      <% end %>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_carousel.html.erb
<div id="carousel">
  <%= image_tag "rails.png", height: "410" %>
  <%= image_tag "ruby.jpg", height: "410" %>
  <%= image_tag "stimulus.webp", height: "410" %>
</div>

app/views/users/_error.html.erb
<li><%= error %></li>

app/views/users/_form.html.erb
<%= form_with model: @user, data: { turbo: false, remote: true }, class: 'form' do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/_friend_request.html.erb
<li id=<%= dom_id(sender, :friend_request)  %>>
  <p> Name: <%= sender.first_name %> </p>
  <%= button_to 'Accept', friendships_path, params: { sender_id: sender.id } %>
  <button>Reject</button>
</li>

app/views/users/_other_profile.html.erb
<section>
  <h2>Profile</h2>

  <section>
    <h3>Details</h3>

    <p>Name: <%= @user.first_name %></p>
    <%# check whether user is a friend and only then
      display the email %>
    <p>Email: <%= @user.email %></p>
  </section>

  <!--
  <section>
    <h3>Friendship Status</h3>

    <% if current_user.sent_friend_reqs.to(@user) %>
      <p>Pending....</p>
    <% elsif current_user.received_friend_reqs.custom_from(@user) %>
      <%= render 'friend_request', sender: @user %>
    <% else %>
      <%= button_to 'Add Friend', friend_requests_path, params: { receiver_id: @user.id } %>
    <% end %>
  -->
  </section>
</section>

app/views/users/_profile.html.erb
<section>
  <h2>Profile</h2>

  <section>
    <h3>Details</h3>
    <p>Name: <%= @user.first_name %></p>
    <p>Email: <%= @user.email %></p>
  </section>

  <!--
  <section id="pending_requests">
    <h3>Pending Requests</h3>
    <ul>
      <%= render partial: 'friend_request', 
        collection: @user.friend_req_senders, as: :sender %>
    </ul>
  </section>
  -->
</section>

app/views/users/index.html.erb
<section>
  <h2>All Users </h2>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.first_name + ' ' + user.last_name, user %>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/new.html.erb
<section>
  <h2>Signup</h2>
  <% if @user.errors.any? %>
    <ul id="error_explanation" >
      <%= render partial: 'error', collection: @user.errors.full_messages %>
    </ul>
  <% end %>
  <%= render "form" %>
</section>

app/views/users/show.html.erb
<% if params[:id].to_i == current_user.id %>
  <%= render 'profile'  %>
<% else %>
  <%= render 'other_profile' %>
<% end %>